DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Askare CASCADE;
DROP TABLE IF EXISTS Prioriteetti CASCADE;
DROP TABLE IF EXISTS AskareLuokka CASCADE;
DROP TABLE IF EXISTS Luokka CASCADE;

